USE [master]
GO

/****** Object:  Database [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF]    Script Date: 3/31/2014 12:51:28 PM ******/
CREATE DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DataBase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\DataBase.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DataBase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\DataBase_log.ldf' , SIZE = 528KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET ARITHABORT OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET  DISABLE_BROKER 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET  MULTI_USER 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [C:\USERS\EGOR\DESKTOP\ASP\MVCAPPLICATION2\MVCAPPLICATION2\APP_DATA\DATABASE.MDF] SET  READ_WRITE 
GO

